version: '3'

services: 
    server: 
        build: ./server
        volumes: 
            - ./server:/usr/src/app
        ports: 
            - 8081:8081
    client: 
        build: ./client
        volumes: 
            - ./client:/usr/src/app
        ports: 
            - 8080:8080
        depends_on: 
            - server